name: Build wheels

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels (manylinux)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # Set up Python (this step is optional; cibuildwheel will use containerized Pythons)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install cibuildwheel so we can build manylinux wheels
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      # Build wheels using cibuildwheel in a manylinux container.
      # The CIBW_BEFORE_BUILD script runs inside the container and installs pybind11 from the submodule,
      # builds Boost, and builds ZeroMQ, installing them into /tmp/local.
      - name: Build wheels with cibuildwheel
        env:
          CIBW_BEFORE_BUILD: |
            # Remove Python 3.6 if it exists
            yum remove -y python36 python3.6 python36-devel python3.6-devel || true
            
            # Install system dependencies
            yum install -y wget gcc gcc-c++ make python3-devel python3-libs
            
            
            # Debug: show Python information
            echo "Python executable: $(which python)"
            python --version
            
            #Python path detection
            PYBIN=$(which python)
            PYTHON_VERSION=$(python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
            PYTHON_ROOT=$(cd $(dirname $PYBIN)/..; pwd)
            PYTHON_INCLUDE=$PYTHON_ROOT/include/python${PYTHON_VERSION}*
            PYTHON_LIB=$PYTHON_ROOT/lib*/libpython${PYTHON_VERSION}*.so
            
            # Set CMake arguments for Python
            export PATH="$PYTHON_ROOT/bin:$PATH"
            export PYTHON_EXECUTABLE="$PYBIN"
            export CMAKE_ARGS="-DPython_EXECUTABLE=$PYBIN -DPython_ROOT_DIR=$PYTHON_ROOT -DPython_INCLUDE_DIR=$PYTHON_INCLUDE -DPython_LIBRARY=$PYTHON_LIB"
            export PYTHONPATH=$PYTHON_ROOT/lib/python${PYTHON_VERSION}/site-packages
            
            # Install Python build tools
            python -m pip install --upgrade pip
            python -m pip install wheel scikit-build cmake ninja setuptools
            
            
            echo "Using Python at: $PYBIN"
            echo "Python version: $PYTHON_VERSION"
            echo "Python root: $PYTHON_ROOT"
            echo "Python include: $PYTHON_INCLUDE"
            echo "Python lib: $PYTHON_LIB"
            
            # Debug Python installations
            #echo "Available Python installations:"
            #find / -name "python*" -type f -executable 2>/dev/null | grep -v "config\|/site-packages/" | sort
            
            cmake -DPython_EXECUTABLE=$PYBIN -DPython_ROOT_DIR=$PYTHON_ROOT -DPython_INCLUDE_DIRS=$PYTHON_INCLUDE -DPython_LIBRARY=$PYTHON_LIB ..
            
             # Debug: Find Python headers and libraries
            echo "Searching for Python headers..."
            find $PYTHON_ROOT -name "Python.h" || echo "Python.h not found in $PYTHON_ROOT"
            echo "Searching for Python libraries..."
            find $PYTHON_ROOT -name "libpython*.so*" || echo "libpython*.so not found in $PYTHON_ROOT"
              
            # Build and install pybind11 from the submodule
            cd pybind11
            mkdir -p build && cd build
            cmake .. -DPYBIND11_PYTHON_VERSION=3.10 \ 
                     -DPython_EXECUTABLE=$PYBIN \
                     -DPython_ROOT_DIR=$PYTHON_ROOT \
                     -DPython_INCLUDE_DIR=$PYTHON_INCLUDE \
                     -DPython_LIBRARY=$PYTHON_LIB
            make && make install
            cd ../..
            
            # Download, build, and install static Boost
            mkdir -p /tmp/deps
            cd /tmp/deps
            wget -q https://archives.boost.io/release/1.79.0/source/boost_1_79_0.tar.gz
            tar xf boost_1_79_0.tar.gz
            cd boost_1_79_0
            ./bootstrap.sh --with-libraries=system,filesystem --prefix=/tmp/local
            ./b2 link=static install
            cd ..
            
            # Download, build, and install static ZeroMQ
            git clone https://github.com/zeromq/libzmq.git
            cd libzmq
            ./configure --enable-static --disable-shared --prefix=/tmp/local
            mkdir build && cd build
            cmake .. && sudo make -j4 install
            cd ../..
            
            git clone https://github.com/zeromq/cppzmq.git
            cd cppzmq && mkdir build && cd build
            cmake -DCPPZMQ_BUILD_TESTS=OFF .. && sudo make -j4 install
            cd ../../
            
            #wget https://github.com/zeromq/libzmq/releases/download/v4.3.4/zeromq-4.3.4.tar.gz
            #if [ $? -ne 0 ]; then echo "ZeroMQ download failed"; exit 1; fi
            #ls -la
            tar xf zeromq-4.3.4.tar.gz
            #cd zeromq-4.3.4
            #./configure --enable-static --disable-shared --prefix=/tmp/local
            #make -j4
            #make install
            
            echo "Installing ZeroMQ C++ bindings..."
            cd /tmp/deps
            git clone https://github.com/zeromq/cppzmq.git
            cd cppzmq
            mkdir build && cd build
            cmake .. -DCMAKE_INSTALL_PREFIX=/tmp/local
            make -j4 && make install
            
            # Create symlinks if needed
            ln -sf $PYTHON_LIB $PYTHON_ROOT/lib/$(basename $PYTHON_LIB)

            # Make a simple Python test file to verify we're using the right Python
            echo "import sys; print(f'Building for Python {sys.version}')" > /tmp/test.py
            $PYBIN /tmp/test.py
          # Use a manylinux image with an older toolchain
          CIBW_BASE_IMAGE: quay.io/pypa/manylinux2010_x86_64

          # Pass the dependency install prefix to CMake
          CIBW_ENVIRONMENT: >
            CMAKE_PREFIX_PATH=/tmp/local
            BOOST_ROOT=/tmp/local
            ZeroMQ_ROOT=/tmp/local
            CMAKE_ARGS="-DBUNDLE_DEPENDENCIES=ON -DSKBUILD=ON -DPython_FIND_COMPONENTS=Interpreter;Development -DPython_LIBRARIES=$PYTHON_LIB -DPython_LIBRARY=$PYTHON_LIB"

          # Specify which Python versions to build for
          CIBW_BUILD: "cp310-* cp311-*"

          # Skip tests during wheel building
          CIBW_TEST_SKIP: "*"

        run: python -m cibuildwheel --output-dir wheelhouse

      # Upload the resulting wheels as artifacts
      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheelhouse/*.whl
