name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: build tests
        run: mkdir cmake-build-debug-coverage && cd cmake-build-debug-coverage
cmake ../ -DCODE_COVERAGE=ON && cmake --build . --target unit_test --config Release -- -j
