name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: list dir
        run: ls
      - name: make dir
        run: mkdir cmake-build-debug-coverage 
      - name: cd dir
        run: cd cmake-build-debug-coverage
      - name: makefile
        run: cmake ../ -DCODE_COVERAGE=ON
      - name: build tests 
        run: cmake --build . --target unit_test --config Release -- -j
      - name: run test
        run: ./unit_test
      - name: capture coverage 
        run: lcov --capture --directory . --output-file coverage.info 
      - name: clean coverage
        run: lcov --remove coverage.info '*/include/*' '*/eigen/*' '*test/*' -o coverage.info 
