name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt install -y libcppunit-dev
          sudo apt-get install software-properties-common
          sudo apt install -y lcov
      - name: cmake installation
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v3.22.5/cmake-3.22.5.tar.gz
          tar -zxvf cmake-3.22.5.tar.gz
          cd cmake-3.22.5
          sudo ./bootstrap
          sudo make
          sudo make install
          cmake --version
      - name: git submodule installation
        run: |
          git submodule init
          git submodule update
      - name: make project
        run: |
          mkdir cmake-build-debug-coverage
          cd cmake-build-debug-coverage
          cmake ../ -DCODE_COVERAGE=ON
          cmake --build . --target unit_test --config Release -- -j
      - name: run tests and get coverage
        run: |
          ./unit_test
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '*/include/*' '*/eigen/*' '*test/*' -o coverage.info
          COVERAGE=$(genhtml coverage.info --output-directory out | grep -Po 'lines......: \K[^%]*')
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 7d4c25ef2e97e8de523ef7c1fee26e8e
          filename: treeCoreset__${{ env.BRANCH }}.json
          label: Test Coverage
          message: ${{ env.COVERAGE }}
          color: green
          namedLogo: jest
